export type Lang = 'en' | 'zh';
export const COPY = {
  en: {
    play: 'Play',
    tag: 'Draw. Drive. Deliver.',
    intro: 'A tiny city. One van. Your way through.',
    start: 'Start Game',
    about: 'Three quick rounds · about a minute',
    load: 'Waking up the city…',
    tutorial: 'Draw a route to the glowing building.',
    nice: 'Nice. Now connect them all.',
    draw: 'Draw from the van. Release to drive.',
    score: 'Score',
    time: 'Time',
    fuel: 'Fuel',
    deliveries: 'Deliveries',
    pause: 'Pause',
    resume: 'Resume',
    restart: 'Restart',
    exit: 'Exit game',
    soundOn: 'Turn sound on',
    soundOff: 'Turn sound off',
    undo: 'Undo',
    clear: 'Clear route',
    drive: 'Drive route',
    keyboard: 'Keyboard',
    keys: 'Arrow keys: draw along streets · Enter: drive · Backspace: undo · Esc: clear · Space: pause',
    touch: 'Draw along the streets. Lift your finger to drive.',
    paused: 'Take a breather.',
    pausedHint: 'Your route will be here.',
    offscreen: 'Paused while you explore',
    level: 'ROUND',
    combo: 'COMBO',
    perfect: 'Perfect Route ×3',
    coffee: 'Coffee Boost!',
    express: 'Express delivered +1,100',
    expressLive: 'Express is here',
    traffic: 'A quick traffic stop…',
    road: 'Stay near a street.',
    blocked: 'Road closed. Try the next street.',
    outFuel: 'That route needs more fuel.',
    startAt: 'Start at the van.',
    complete: 'Every doorstep. Delivered.',
    timeout: 'Time’s up. A new route awaits.',
    fuelEnd: 'Out of fuel. Try a shorter route.',
    won: 'SPECIAL DELIVERY / COMPLETE',
    ended: 'END OF YOUR RUN',
    again: 'Play Again',
    hard: 'Hard Mode',
    built: 'See How I Built It',
    best: 'Best combo',
    efficiency: 'Route efficiency',
    delivered: 'Delivered',
    scenic: 'You delivered everything. The scenic route was… ambitious.',
    partial:
      'A few doorsteps are still waiting. Try connecting more stops in one route.',
    explain:
      'You just solved a simplified last-mile routing problem: connecting multiple destinations while balancing distance, time and changing road conditions.',
    disclosure:
      'Synthetic interactive experience inspired by real-world delivery systems.',
    twoD: 'Use 2D view',
    threeD: 'Use 3D view',
    cityReady: 'City ready',
    caseTitle: 'From a gesture to a working system.',
    caseIntro:
      'A personal interactive project connecting software engineering, data visualization and experience with last-mile operations.',
    problem: 'Problem',
    problemBody:
      'Make a routing trade-off understandable without knowing logistics terminology.',
    contribution: 'My contribution',
    contributionBody:
      'Designed and implemented the city, gesture controls, road rules, driving simulation and bilingual experience in this portfolio.',
    approach: 'Approach',
    approachBody:
      'One road graph controls pointer snapping, keyboard routes, collisions and vehicle movement. A single simulation clock coordinates fuel, traffic, boosts, weather and scoring. Both renderers use the same game state.',
    outcome: 'Outcome',
    outcomeBody:
      'A playable three-round experience with procedural 3D models and a Canvas fallback. The result is an interactive demonstration, not a measured business outcome.',
    closeCase: 'Close project notes',
    notes: [
      'Interaction Design',
      'Path and Collision Logic',
      'Game State Management',
      'Motion System',
      'Responsive Controls',
    ],
    details: [
      'Draw, release, watch the city respond.',
      'Road snapping and rounded paths share one coordinate system.',
      'Explicit run, pause, level and result states.',
      'Distance-based driving, staged lighting and parcel motion.',
      'Mouse, touch, keyboard and Canvas fallback.',
    ],
    titles: {
      'Route Genius': 'Route Genius',
      'Speed Courier': 'Speed Courier',
      'Smooth Operator': 'Smooth Operator',
      'Express Hero': 'Express Hero',
      'Scenic Driver': 'Scenic Driver',
    },
  },
  zh: {
    play: '游玩',
    tag: '画路线。开车。送达。',
    intro: '一座小城，一辆货车，一条你的路线。',
    start: '开始游戏',
    about: '三关快速挑战 · 约一分钟',
    load: '正在唤醒小城…',
    tutorial: '从仓库画到发光建筑。',
    nice: '很好。现在把它们全部连起来。',
    draw: '从货车开始画线，松手即出发。',
    score: '得分',
    time: '时间',
    fuel: '燃油',
    deliveries: '送达',
    pause: '暂停',
    resume: '继续',
    restart: '重新开始',
    exit: '退出游戏',
    soundOn: '开启声音',
    soundOff: '关闭声音',
    undo: '撤销',
    clear: '清除路线',
    drive: '出发',
    keyboard: '键盘操作',
    keys: '方向键沿街画线 · Enter 出发 · Backspace 撤销 · Esc 清除 · 空格暂停',
    touch: '沿街道画线，抬起手指就出发。',
    paused: '歇一小会儿。',
    pausedHint: '路线会在原地等你。',
    offscreen: '浏览页面时已自动暂停',
    level: '第',
    combo: '连击',
    perfect: '完美路线 ×3',
    coffee: '咖啡加速！',
    express: '限时快件送达 +1,100',
    expressLive: '金色快件出现了',
    traffic: '等一会儿，马上通畅…',
    road: '请沿着街道画线。',
    blocked: '道路施工，试试旁边的街道。',
    outFuel: '这条路线需要更多燃油。',
    startAt: '请从货车开始。',
    complete: '每一个门口，都已送达。',
    timeout: '时间到。下一条路线会更好。',
    fuelEnd: '燃油用尽，试试更短的路线。',
    won: '特别配送 / 挑战完成',
    ended: '本次挑战结束',
    again: '再玩一次',
    hard: '困难模式',
    built: '看看我是怎么做的',
    best: '最佳连击',
    efficiency: '路线效率',
    delivered: '已送达',
    scenic: '全部送达。只是这条观光路线……很有雄心。',
    partial: '还有几个门口在等你。试着用一条路线串起更多目的地。',
    explain:
      '你刚刚解决了一个简化的末端配送路线问题：在距离、时间和变化的道路状况之间连接多个目的地。',
    disclosure: '受真实配送系统启发的合成交互体验，不含公司数据。',
    twoD: '切换 2D 视图',
    threeD: '切换 3D 视图',
    cityReady: '小城已就绪',
    caseTitle: '从一个手势，到一个完整系统。',
    caseIntro:
      '个人交互项目，将软件工程、数据可视化与末端物流运营经验连接起来。',
    problem: '问题',
    problemBody: '让不了解物流的人，也能亲手感受路线选择的取舍。',
    contribution: '我的工作',
    contributionBody:
      '在个人网站中设计并实现城市模型、手势操作、道路规则、驾驶模拟与双语体验。',
    approach: '实现方法',
    approachBody:
      '同一张道路图负责手势吸附、键盘画线、碰撞与车辆移动。统一时钟协调燃油、交通、加速、天气与评分。两种画面模式共享游戏状态。',
    outcome: '结果',
    outcomeBody:
      '可实际游玩的三关体验，包含程序化 3D 建模与 Canvas 降级。这是个人交互演示，不代表已量化的工作成果。',
    closeCase: '收起项目说明',
    notes: [
      '交互设计',
      '路线与碰撞逻辑',
      '游戏状态管理',
      '动效系统',
      '响应式操作',
    ],
    details: [
      '画线、松手，看城市回应。',
      '道路吸附和圆角路线使用同一坐标。',
      '明确管理游玩、暂停、关卡与结算。',
      '按距离驾驶，逐层亮灯，包裹动态送入。',
      '鼠标、触屏、键盘与 Canvas 降级。',
    ],
    titles: {
      'Route Genius': '路线天才',
      'Speed Courier': '闪电快递员',
      'Smooth Operator': '丝滑驾驶员',
      'Express Hero': '快件英雄',
      'Scenic Driver': '风景探索家',
    },
  },
};
